site_name: Litrepl Docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - General concepts: usage/general-concepts.md
    - Formatting documents: usage/formatting.md
    - Vim plugin: usage/vim-plugin.md
    - How-Tos: usage/application-scenarios.md
  - Development:
    - Common scenarios: development/common-scenarios.md
    - Advanced: development/more-scenarios.md
    - Insights and limitations: development/insights-limitations.md
  - Reference:
    - Command line and Vim: reference.md
  - Related projects: related.md
theme: readthedocs
markdown_extensions:
  - markdown_include.include:
      base_path: docs
