site_name: Litrepl Docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - General concepts: usage/general-concepts.md
    - Formatting: usage/formatting.md
    - Vim plugin: usage/vim-plugin.md
    - Application Scenarios: usage/application-scenarios.md
  - Reference: reference.md
  - Development: development.md
  - Related: related.md
theme: readthedocs
markdown_extensions:
  - markdown_include.include:
      base_path: docs
